"""FK indexes, jti unique, orders index

Revision ID: 6cbc5e78c930
Revises: 811a9e32df72
Create Date: 2026-03-18 14:29:42.732156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cbc5e78c930'
down_revision = '811a9e32df72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index('ix_order_items_order_id', ['order_id'], unique=False)
        batch_op.create_index('ix_order_items_product_id', ['product_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('panier', schema=None) as batch_op:
        batch_op.create_index('ix_panier_product_id', ['product_id'], unique=False)
        batch_op.create_index('ix_panier_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_order_id', ['order_id'], unique=False)
        batch_op.create_index('ix_transactions_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_user_id')
        batch_op.drop_index('ix_transactions_order_id')

    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=False)

    with op.batch_alter_table('panier', schema=None) as batch_op:
        batch_op.drop_index('ix_panier_user_id')
        batch_op.drop_index('ix_panier_product_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_user_id')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index('ix_order_items_product_id')
        batch_op.drop_index('ix_order_items_order_id')

    # ### end Alembic commands ###
