"""add unique constraint on panier user_product

Revision ID: 8623ead4f42b
Revises: 6cbc5e78c930
Create Date: 2026-03-24 16:53:19.184407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8623ead4f42b'
down_revision = '6cbc5e78c930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panier', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_panier_user_product', ['user_id', 'product_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panier', schema=None) as batch_op:
        batch_op.drop_constraint('uq_panier_user_product', type_='unique')

    # ### end Alembic commands ###
